[package]
name = "app"
version = "0.0.1"
authors = [
  "CyberHoward <cyberhoward@protonmail.com>",
  "Adair <adair@abstract.money>",
  "Abstract Money <contact@abstract.money>",
]
edition = "2021"
homepage = ""
documentation = ""
repository = ""
license = "GPL-3.0-or-later"
keywords = ["cosmos", "cosmwasm", "abstractsdk"]

# Enable the version 2 feature resolver, which avoids unifying features for targets that are not being built
#
# Critically this prevents dev-dependencies from enabling features even when not building a target that
# uses dev-dependencies, e.g. the library crate. This in turn ensures that we can catch invalid feature
# flag combinations that would otherwise only surface in dependent crates
#
# Reference - https://doc.rust-lang.org/nightly/cargo/reference/features.html#feature-resolver-version-2
# See - https://github.com/apache/arrow-rs/pull/1822/files
resolver = "2"

exclude = ["contract.wasm", "hash.txt"]

[lib]
crate-type = ["cdylib", "rlib"]

[[example]]
name = "schema"
required-features = ["schema"]

[features]
default = ["export"]
export = []
interface = ["export", "dep:abstract-interface", "dep:cw-orch"]
schema = ["abstract-app/schema"]

[dependencies]
cosmwasm-std = { version = "1.1" }
cosmwasm-schema = { version = "1.1" }
cw-controllers = { version = "1.0.1" }
cw-storage-plus = "1.0.1"
thiserror = { version = "1.0" }
schemars = "0.8"
cw-asset = { version = "3.0" }

abstract-core = { git = "https://github.com/AbstractSDK/contracts.git" }
abstract-app = { git = "https://github.com/AbstractSDK/contracts.git" }
abstract-sdk = { git = "https://github.com/AbstractSDK/contracts.git" }

# Dependencies for interface
abstract-interface = { git = "https://github.com/AbstractSDK/contracts.git", optional = true }
cw-orch = { version = "0.12", optional = true }

[dev-dependencies]
app = { path = ".", features = ["interface"] }
abstract-interface = { git = "https://github.com/AbstractSDK/contracts.git", features = [
  "daemon",
] }
abstract-testing = { git = "https://github.com/AbstractSDK/contracts.git" }
abstract-sdk = { git = "https://github.com/AbstractSDK/contracts.git", features = [
  "test-utils",
] }
speculoos = "0.11.0"
semver = "1.0"
dotenv = "0.15.0"
env_logger = "0.10.0"
cw-orch = { version = "0.12", features = ["daemon"] }
